const router = require('express').Router();
const { randomUUID } = require('node:crypto');
const { protect } = require('../middleware/auth');
const controller = require('../controllers/mediaController');
router.use(protect);
router.use((req, res, next) => { req.mediaRequestId = randomUUID(); res.set('X-Request-ID', req.mediaRequestId); res.set('Cache-Control', 'no-store'); next(); });
router.post('/upload/init', controller.init);
router.post('/:id/complete', controller.complete);
router.get('/:id/download', controller.download);
router.get('/:id/content', controller.content);
router.get('/:id', controller.metadata);
router.delete('/:id', controller.remove);
module.exports = router;
