const { randomUUID } = require('node:crypto');
const fail = require('../../utils/httpError');
const types = { 'image/jpeg': ['images', 'jpg'], 'image/png': ['images', 'png'], 'image/webp': ['images', 'webp'], 'video/mp4': ['videos', 'mp4'], 'video/webm': ['videos', 'webm'], 'application/pdf': ['documents', 'pdf'] };
const limits = { images: 10 * 1024 * 1024, documents: 20 * 1024 * 1024, videos: 512 * 1024 * 1024, reels: 100 * 1024 * 1024 };
function validate(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw fail(400, 'Invalid media request');
  if (Object.hasOwn(input, 'storageKey')) throw fail(400, 'Object keys are generated by the server');
  if (input.filename !== undefined && (typeof input.filename !== 'string' || input.filename.length > 255 || /[\\/\x00-\x1f\x7f]/.test(input.filename) || input.filename === '.' || input.filename === '..')) throw fail(400, 'Invalid filename');
  const type = types[input.mimeType];
  if (!type || !(input.category === type[0] || input.category === 'reels' && type[0] === 'videos')) throw fail(400, 'Unsupported media category or MIME type');
  if (!Number.isSafeInteger(input.size) || input.size < 1 || input.size > limits[input.category]) throw fail(400, 'Invalid media size');
  if (typeof input.checksum !== 'string' || !/^[A-Za-z0-9+/]{43}=$/.test(input.checksum) || Buffer.from(input.checksum, 'base64').toString('base64') !== input.checksum) throw fail(400, 'A SHA-256 base64 checksum is required');
  return type[1];
}
function key(category, extension) {
  // Opaque random owner namespace avoids leaking internal account IDs.
  const date = new Date();
  return `originals/${category}/${randomUUID()}/${date.getUTCFullYear()}/${String(date.getUTCMonth() + 1).padStart(2, '0')}/${randomUUID()}.${extension}`;
}
async function validateBytes(bytes, mimeType) {
  let detected;
  try { detected = await (await import('file-type')).fileTypeFromBuffer(bytes); }
  catch { throw fail(400, 'Invalid media content'); }
  if (detected?.mime !== mimeType) throw fail(400, 'File content does not match its media type');
}
module.exports = { validate, key, validateBytes, limits };
