module.exports = {
  COIN_VALUES: {
    WATCH_VIDEO: 10,
    INSTAGRAM_FOLLOW: 50,
    INSTAGRAM_LIKE: 20,
    YOUTUBE_SUBSCRIBE: 100,
    REFERRAL_BONUS: 500,
    POST_UPLOAD: 30,
    DAILY_LOGIN: 25,
  },
  MIN_WITHDRAWAL_AMOUNT: 1000,
  COIN_TO_RUPEE_RATE: 100,
  VIDEO_WATCH_PERCENTAGE: 80,
};

